public enum TypesOfCells {
    STARTINGPOINT,
    SVISLAZEZHORA,
    SVISLAZEZDOLA,
    VODOROVNAZLEVA,
    VODOROVNAZPRAVA,
    ZEZHORADOPRAVA,
    ZEZHORADOLEVA,
    ZEZDOLADOPRAVA,
    ZEZDOLADOLEVA,
    BLANK,
}
